# Generated by Django 5.0.6 on 2024-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_truck_finder', '0002_alter_foodcartdetail_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Applicant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Approved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='ExpirationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='FacilityType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='FirePreventionDistricts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='FoodItems',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='LocationDescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='NOISent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Neighborhoods',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='PoliceDistricts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='PriorPermit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Received',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='SupervisorDistricts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='X',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='Y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='ZipCodes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='blocklot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='cnn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='dayshours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='lot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodcartdetail',
            name='permit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
